name: API Tests with Newman

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      # Add database service if needed
      # postgres:
      #   image: postgres:13
      #   env:
      #     POSTGRES_USER: postgres
      #     POSTGRES_PASSWORD: postgres
      #     POSTGRES_DB: test_db
      #   ports:
      #     - 5432:5432
      #   options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Django server in background
        run: |
          python manage.py migrate
          nohup python manage.py runserver 0.0.0.0:8000 &
          sleep 5  # Give the server time to start
          
      - name: Install Newman
        run: |
          npm install -g newman
          
      - name: Create Postman environment file
        run: |
          echo '{
            "id": "test-environment",
            "name": "Test Environment",
            "values": [
              {
                "key": "base_url",
                "value": "http://localhost:8000",
                "enabled": true
              }
            ]
          }' > postman_environment.json
          
      - name: Run Newman tests
        run: |
          newman run postman_collection.json -e postman_environment.json
          
      - name: Generate HTML report (optional)
        if: always()  # Run even if tests fail
        run: |
          npm install -g newman-reporter-htmlextra
          newman run postman_collection.json -e postman_environment.json -r htmlextra --reporter-htmlextra-export ./newman-report.html
          
      - name: Upload test results
        if: always()  # Run even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: ./newman-report.html 